<div class="content-container">
    <div class="container-fluid">
        <h2 class="h2-404">A jéje, 404.</h2>
        <p class="p-404">V copywriterské věži asi straší.<br>Pojďte radši <a href="/uvodni-strana">domů</a> </p>

        <div class="red-line-404"></div>

        <div class="h1-image-404 row">
                <h1 class="col-lg-9 margined-top-30-h1">Chcete taky neotřelou chybovou stránku?<br>Není problém. <a href="/kontakt">Plácneme si?</a> </h1>
            <div class="col-lg-3">
                <img src="../img/bump.png" alt="Plácneme si!">
            </div>
        </div>

    </div>
</div>