
    <div class="homepage-container-upper">
        <div class="content-container">
            <div class="container-fluid row">




                    <div class="homepage-upper-heading col-lg-8">
                        <h1 class="h1-homepage">Chcete na web špičkové texty, ale máte z psaní závratě?<br><br></h1>
                        <h2 class="h2-homepage">Vyšplhám pro ně za vás!</h2>
                        <a href="#" class="btn cta-jak-to-delam button button--moema button--text-upper button--size-s" >Jak to dělám?</a><br>
                        <div class="homepage-arrow-container">
                            <a href="#" class="arrow-down-white"><img src="../img/svg/arrow-down-white.svg"></a>
                        </div>

                    </div>

                    <div class="tower-top-homepage-container col-lg-4">
                        <div class="tower-top">
                    <!-- <img src="../img/tower-top.png" class="tower-top-homepage">-->
                        </div>
                    </div>



            </div>
        </div>
    </div>


    <div class="content-container">
        <div class="container-fluid">
            <div class="homepage-middle-line row">
                <div class="col-lg-8 homepage-middle-left-text">
                    <h3 class="h3-homepage-klienti">Co na mě práskli klienti?</h3>
                    <div class="red-line-homepage"></div>
                    <div class="row jana-container">
                        <div class="jana col-lg-1">
                            <img src="../img/clients/janca-spst.jpg">
                        </div>
                        <div class="jana-text jana-homepage col-lg-5">
                            <h3 class="h3-jana">Ing. Jana Vacková</h3>
                            <p class="p-jana">koordinátorka propagace SPŠT</p>
                        </div>
                    </div>
                    <div class="jana-citace-homepage">
                        <p class="homepage-citace">
                            „Na Romanovi oceňuji vysokou profesionalitu, ochotu pomoci, spolehlivost, zajímavé a svěží
                            nápady, včasné odevzdání projektu a zejména to nejdůležitější – dokáže kouzlit se slovy.“
                        </p>
                    </div>
                    <a href="/reference" class="btn cta-homepage-dalsi-klienti button button--moema button--text-upper button--size-s" >Další okouzlení klienti</a><br>
                </div>
                <div class="col-lg-4 homepage-middle-right-tower">
                    <img src="../img/tower-middle.png" alt="Roman Věžník, věž, schody">
                </div>
            </div>
        </div>
    </div>

    <img src="../img/tower-top-1.png" class="test">
    <img src="../img/tower-top-2.png" class="test">
    <img src="../img/tower-top-3.png" class="test">
    <img src="../img/tower-top-4.png" class="test">