<div class="content-container">
    <div class="container-fluid">

            <h1 class="h1-contact">Potřebujete špičkové texty?<br>Není problém. Napište mi.</h1>
            <div class="red-line-404"></div>

        <div class="row contact-container ">
                <div class="col-lg-6 no-padding-margin-contact-container">
                <h3 class="h3-contact-mail-roman"><a href="mailto:roman@veznik.cz">roman@veznik.cz</a></h3>
                <h4 class="h4-contact">Proč tu není mobilní kontakt?</h4>
                <p class="p-mobil-contact">
                    Mám-li vykouzlit super text či nápad, potřebuji, aby mé šedé
                    buňky mozkové mířily pouze do jednoho terče. Než je tam
                    nasměřuji, krapet to trvá. Ale jakmile chytnu flow, vezu se<br>
                    jako surfař na megavlně a tvořím a tvořím. Když vtom…
                </p>
                <h4 class="h4-contact sec">Kde tvořím?</h4>
                    <p class="contact-kde-tvorim">
                       <strong> Šajby 502<br>
                        675 55 Hrotovice
                       </strong>
                        <br><br>
                        Pečlivě na mě dohlíží OOŽÚ města Třebíče, kde jsem jako
                        <strong>neplátce DPH</strong> Mgr. Roman Věžník zapsán v živnostenském
                        rejstříku pod IČ <strong>71567046.</strong><br>
                        Uff, to je tasemnice. Ale povinnostem bylo učiněno zadost.
                    </p>
                </div>
                <div class="col-lg-6 no-padding-margin-contact-container form-container">
                    <h3 class="h3-contact-form">Bleskový kontakt</h3>
                    <form method="post">
                        <div class="form-group">
                            <label for="name">Vaše jméno/firma</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                            <div class="row">
                                <div class="col-lg-6">
                                    <label for="phone">Telefon</label>
                                    <input type="text" class="form-control" id="phone" name="phone" required>
                                </div>
                                <div class="col-lg-6">
                                    <label for="email">E-mail</label>
                                    <input type="email" class="form-control" id="email" name="email" required>
                                </div>
                            </div>
                            <label for="message">S čím vám můžu pomoci?</label>
                            <textarea class="form-control" id="message" rows="5" name="message" required></textarea>
                            <br>
                            <input type="submit" class="btn cta-send-email float-right button button--moema button--text-upper button--size-s" value="Poslat zprávu" name="send">
                        </div>
                    </form>
                </div>
            </div>
    </div>
</div>