<div class="content-container">
    <div class="container-fluid">
        <h2 class="h2-reference">Okouzlení klienti o mně bez mučení kápli božskou</h2>

        <div class="red-line-reference"></div>

        <div class="row jana-container">
            <div class="jana col-lg-1">
                <img src="../img/clients/janca-spst.jpg">
            </div>
            <div class="jana-text col-lg-4">
                <h3 class="h3-jana">Ing. Jana Vacková</h3>
                <p class="p-jana">koordinátorka propagace SPŠT</p>
            </div>
        </div>

        <img src="../img/svg/arrow-shape.svg" class="arrow-shape">
        <div class="row container-clanek-social">
            <div class="jana-clanek-container col-lg-10">
                <p>
                    „Microsite Pojď na SPŠT je projekt, na kterém se podílel Roman Věžník. Tato stránka podává pomocnou
                    ruku žákům ZŠ při výběru dalšího studia. Roman řídil celý projekt, texty přizpůsobil cílové skupině.
                    Zvolený jazyk a tón komunikace vhodně zapadá do konceptu propagační kampaně školy.
                </p>
                <p>
                    V průběhu náborové kampaně připravoval texty k jednotlivým vzdělávacím oblastem na oficiální
                    facebookovou stránku školy.
                </p>
                <p>
                    Na Romanovi oceňuji vysokou profesionalitu, ochotu pomoci, spolehlivost, zajímavé a svěží nápady,
                    včasné odevzdání projektu a zejména to nejdůležitější – dokáže kouzlit se slovy.“
                </p>
            </div>
            <div class="col-lg-2 reference-social">
                <div class="social-item row">
                    <div class="rect active-rect"></div><span class="active-rect-text">Web</span>
                </div>
                <div class="social-item row">
                    <div class="rect"></div><span class="rect-text">Facebook</span>
                </div>
                <div class="social-item row">
                    <div class="rect"></div><span class="rect-text">Konzultace</span>
                </div>

            </div>
        </div>


        <h3 class="h3-sedmero-referenci">Sedmero srdcových referencí</h3>
        <div class="row reference-container">
            <div class="col-lg-6 reference-firma upper">
                <img src="../img/svg/ref-logos/spst-logo.svg" alt="SPŠT, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">Pojď na SPŠT</h4>
                <p class="reference-firma-text">
                    Náborovou microsite jsem nejen textoval, ale taky celou
                    vymýšlel. V osvědčeném tandemu s grafikem <a href="https://www.alesmejzlik.cz/">Alešem
                    Mejzlíkem</a>. I nadále v tom s třebíčskou průmkou lítáme
                    a tvoříme například náborové posty pro její <a href="https://www.facebook.com/SPSTrebic/photos/a.340132952759840.66803.328315407274928/998638690242593/?type=3">Facebook</a>.<br>
                </p>
                <h5 class="reference-firma-social"><a href="https://www.pojdnaspst.cz/?utm_source=spst.cz&utm_medium=web&utm_campaign=sidebar">www</a>|<a href="https://www.facebook.com/SPSTrebic/?fref=ts">Facebook</a></h5>
            </div>
            <div class="col-lg-6 reference-firma upper second">
                <img src="../img/svg/ref-logos/srv-logo.svg" alt="Slavnosti růžového vína, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">Slavnosti růžového vína</h4>
                <p class="reference-firma-text">
                    S <a href="https://www.alesmejzlik.cz/">Alešem</a> jsme v online světě také úspěšně rozlévali Růžovou
                    pohodu. Já vymyslel wireframy, on je oblékl do příjemné
                    grafiky. Mezitím postupně uzrály moje texty. Jako víno.
                    Společně s kampaní na <a href="https://www.facebook.com/slavnostiruzovehovina/">sociálních sítích</a> a offline reklamou se
                    nám oproti prvnímu ročníku povedlo nalákat do zámeckého
                    parku více než desetinásobek růžových pohodářů.
                    <br>
                </p>
                <h5 class="reference-firma-social"><a href="https://www.slavnostiruzovehovina.cz/">www</a>|<a href="https://www.facebook.com/slavnostiruzovehovina/">Facebook</a></h5>
            </div>


            <div class="col-lg-6 reference-firma">
                <img src="../img/svg/ref-logos/cerstva-svaca-logo.svg" alt="Čerstvá sváča, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">Čerstvá sváča</h4>
                <p class="reference-firma-text">
                    Moje první velká copy výzva. Což o to. Napsat texty pro web,
                    to byla ještě copy rozcvička. Ale vymyslet dvacet netuctových
                    názvů svačin a po roce vytáhnou z rukávu další dva tucty, to
                    už zavánělo vztyčeným prstem. Jen si vybrat kterým. ;-)
                    Dodnes pečuji o to, aby info na Facebooku a Instagramu bylo
                    vždy čerstvé a příjemně křupavé.
                    <br>
                </p>
                <h5 class="reference-firma-social"><a href="https://www.cerstvasvaca.cz/">www</a>|<a href="https://www.facebook.com/CerstvaSvaca">Facebook</a>|<a href="https://www.instagram.com/cerstvasvaca.cz/">Instagram</a> </h5>
            </div>
            <div class="col-lg-6 reference-firma">
                <img src="../img/svg/ref-logos/obleczech-logo.svg" alt="ObleCzech, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">ObleCzech</h4>
                <p class="reference-firma-text">
                    Nejsem žádnej manekýn, ale ObleCzech mě dostal už svým geniálním názvem.
                    Stojaté vody e-shopové se nám postupně daří rozhoupávat k nákupní akci hlavně díky
                    placeným reklamám na Facebooku. Aleš je oblečkuje do slušivého hávu, já jim dodám
                    správnou dávku copywritingu a pošlu do boje <a href="https://www.facebook.com/business/help/651294705016616">pixely</a>.
                    <br>
                </p>
                <h5 class="reference-firma-social"><a href="https://www.facebook.com/ObleCzech/">www</a></h5>
            </div>

            <div class="col-lg-6 reference-firma">
                <img src="../img/svg/ref-logos/litobal-logo.svg" alt="Litobal, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">Litobal</h4>
                <p class="reference-firma-text">
                    Až s třetím "průmyslovým" webem jsem fakt spokojen. Při pohledu na ty první dva mi srdce drásá
                    pár dětských nemůcek, na které už sice mám lék, ale nemůžu ho aplikovat. Pro vás je to ale skvělá
                    zpráva – už vím, jak na to poladit, aby vše šlapalo jak na drátkách. Texty pro Litobal vznikaly na
                    základě důkladných analýz. Vyplatilo se.
                    <br>
                </p>
                <h5 class="reference-firma-social"><a href="https://www.litobal.cz/">www</a></h5>
            </div>
            <div class="col-lg-6 reference-firma">
                <img src="../img/svg/ref-logos/pragon-consulting-logo.svg" alt="Pragon Consulting, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">Pragon Consulting</h4>
                <p class="reference-firma-text">
                    Dělat konzultanta úspěšné konzultantské společnosti mi bylo
                    ctí a potěšením zároveň. Pragon potřeboval sjednotit tón
                    a formu komunikace. Jak s klienty, tak i uvnitř týmu.
                    S obojím pomáhám dodnes.
                    <br>
                </p>
                <h5 class="reference-firma-social"><a href="#">Konzultace</a></h5>
            </div>

            <div class="col-lg-6 reference-firma">
                <img src="../img/svg/ref-logos/richard-motors-logo.svg" alt="Richard Motors, logo" class="reference-firma-logo">
                <h4 class="h4-firma-name">Richard Motors</h4>
                <p class="reference-firma-text">
                    Tenhle one page web vznikal přímo ukázkově. Nejdřív jsem
                    firmu fakt dost dobře poznal díky <a href="https://www.facebook.com/richardmotorscz">facebookové kampani</a>. Tu
                    jsem nejen vymýšlel a tvořil, ale také pro ni ošéfoval tři
                    celodenní focení. (Spoušť bravurně mačkal opět <a href="https://www.alesmejzlik.cz/">Aleš</a>.) Pak už
                    šlo psaní microsite jako po másle. A když jsme web spustili,
                    mohl jsem s klidem předat facebookové žezlo zpět do
                    společnosti.

                    <br>
                </p>
                <h5 class="reference-firma-social"><a href="https://www.richardmotors.cz/">www</a>|<a href="https://www.facebook.com/richardmotorscz">Facebok</a></h5>
            </div>
            <div class="col-lg-6 reference-firma">
                <h4 class="h4-nabidka-textu">
                    Nenašli jste tu ukázku z oblasti, která by se aspoň vzdáleně podobala vašemu byznysu?<br><br>
                    <a href="/kontakt">Napište si o ni</a>. Vytáhnu ji ze šuplíku. Nebo budete mít tu výhodu, že ty nejlepší nápady
                    dám právě vám, protože budete první.
                </h4>
            </div>
        </div>

        <div class="reference-before-footer-container row hidden-md-down">
            <div class="reference-before-footer-img-container col-lg-3">
                <img src="../img/bump.png" alt="Plácneme si?">
            </div>
            <div class="col-lg-2"></div>
            <h1 class="h1-reference-before-footer col-lg-7">Chcete taky okouzlit své klienty? Není problém. <a href="/kontakt">Plácneme si?</a></h1>
        </div>

        <div class="reference-before-footer-container row hidden-lg-up">
            <h1 class="h1-reference-before-footer col-lg-7">Chcete taky okouzlit své klienty? Není problém. <a href="/kontakt">Plácneme si?</a></h1>
            <div class="col-lg-2"></div>
            <div class="reference-before-footer-img-container col-lg-3">
                <img src="../img/bump.png" alt="Plácneme si?">
            </div>
        </div>



    </div>
</div>