<div class="content-container">
    <div class="container-fluid">


        <!-- O věžníkovi -->
        <h2 class="o-veznikovi-h2">O mně</h2>
        <div class="row o-veznikovi-title-container">
            <div class="o-veznikovi-title">
                <p>
                    Celý svůj život stojím <strong>rozkročen mezi sportem a kouzlením se slovy.</strong> V obou sférách jsem toho zkusil
                    celkem dost. Zhruba v polovině dosud prožitých dnů se přidala třetí vášeň – svět IT.
                </p>
                <p>
                    Co se sportu týče, nakonec jsem zakotvil u (orientačního) běhu. Pro mou práci je důležitý a nedám
                    si na něj sáhnout: <strong>utíkám před stresem a běhám si pro nápady.</strong>
                </p>
                <p>
                    Zatímco jedničky a nuly mě provázejí po většinu dne, s poměrem sportu a kulturna je to jak na houpačce.
                    <strong>S přibývající kily ubývá sportu a bobtná kulturní hemisféra.</strong>
                    Když už mě nebaví zakrývat všechna zrcadla, na knihy sedá prach a sportovní oblečení nestíhá schnout.
                    Ale ani tehdy nekrním. Neusínám u telky, ale při čtení pohádek svým dětem. A to je po čertech dobrá škola copywritingu.
                </p>
                <p>
                    Teď se tomu všemu snažím dát ten správný balanc. Protože jenom <strong>když je člověk spokojený sám se sebou,
                    může přinášet radost druhým.</strong> Doma. Mezi kamarády. Svou prací. Ale konec moudrostem současného Věžníka.
                    Mrkneme na to, jak se k ní prokousal.
                </p>
            </div>
            <div class="o-veznikovi-foto">
                <img src="../img/roman.jpg" alt="Roman Věžník, Copywriter">
            </div>
        </div>
        <!--// O věžníkovi //-->


        <div id="kotva"></div>
        <h4 class="o-veznikovi-h4" id="timeline">Tady je pár okamžiků z mého života, které mě nakonec nasměrovaly do mé copywriterské věže.</h4>
        <!-- arrow down-->
        <div class="arrow-down-o-veznikovi-container w-100">
            <a href="#timeline" class="chevron-down-o-veznikovi"><img src="../img/svg/arrow-down-red.svg"></a>
        </div>
        <!--// arrow down //-->


        <!-- life story -->


        <div class="life-story-container d-flex justify-content-lg-center justify-content-md-start">



            <div class="life-story-text-left hidden-md-down">

                <div class="left-container-text first-text">

                </div>
                <div class="left-container-text">
                    <p>
                        S kamarádem <strong>zakládám svůj první časopis.</strong> Během<br> základky, střední i vejšky pak šéfuju ještě dalším čtyřem.
                    </p>
                </div>
                <div class="left-container-text">

                </div>
                <div class="left-container-text">
                    <p>
                        Překotné období plné <strong>pubertálních kravin:</strong> Končím<br> s hokejem. První cigareta. Poslední cigareta.
                        <br>(Opakovaně.) Žiju si svůj disco příběh....  Navíc devítka je zadarmo, a tak se stávám přeborníkem v
                        disciplíně: Hoď tašku do kouta a do setmění hraj streetball.
                    </p>
                </div>
                <div class="left-container-text">

                </div>
                <div class="left-container-text">
                    <p>
                        Konečně se dozvídám, kdože je to ten Hrabal.<br> Hustej týpek.
                    </p>
                </div>
                <div class="left-container-text">

                </div>
                <div class="left-container-text">
                    <p>
                        Pořád zapáleně buším do klávesnice, ale poprvé své myšlenky přesouvám z
                        papíru na internet.<br> Během všech dalších roků 21. století, které mi jsou vyměřeny, spravuju
                        hafo webů a některé i vytvářím.<br> Amatérsky, ale <a href="http://www.15.oobtrebic.cz/">s láskou</a>.
                    </p>
                </div>
                <div class="left-container-text">

                </div>
                <div class="left-container-text">
                    <p>
                        Dostalo se mi daru <strong>koukat na svět opět dětskýma očima.</strong> Aspoň přes ramena mých rošťáku.
                        Díky synkovi už ani nemusím číst <a href="https://www.melvil.cz/kniha-zacnete-s-proc/">Sinka, aby věděl, že má začínat s proč</a>. Učím se to od něj.
                        Předtím mi každodenní workshopy na toto téma dopřávaly moje dcerky.
                    </p>
                </div>
                <div class="left-container-text">

                </div>
            </div>



            <div class="container-years">
                <div class="line"><div class="line-red"></div><div class="down-logo"></div></div>
                <div class="year first long">1979</div>
                <div class="year long">1992</div>
                <div class="year long">1994</div>
                <div class="year long">1995</div>
                <div class="year long">1996</div>
                <div class="year long">1998</div>
                <div class="year long">1999</div>
                <div class="year long">2000</div>
                <div class="year long">2004</div>
                <div class="year long">2007</div>
                <div class="year year-before-logo long">2015</div>
                <img src="../img/svg/hat.svg" alt="Roman Věžník, logo">
            </div>


            <div class="life-story-text-right">
                <div class="right-container-text-first long-text">
                    <p>
                        <strong>Geny</strong> jsou vrženy.<br> O děvět měsíců později: Hned <strong>na porodním sále beru sestře z ruky pero</strong> a píšu Ježíškovi. Aby za ten den stihl splašit něco kloudného i pro mě.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p class="hidden-lg-up">
                        S kamarádem <strong>zakládám svůj první časopis.</strong> Během základky, střední i vejšky pak šéfuju ještě dalším čtyřem.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p>
                        Učitelka češtiny mě obviňuje, že jsem <strong>tu slohovku opsal od Hrabala.</strong> Kdo to je? Zatím netuším.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p class="hidden-lg-up">
                        Překotné období plné <strong>pubertálních kravin:</strong> Končím s hokejem. První cigareta. Poslední cigareta.
                        (Opakovaně.) Žiju si svůj disco příběh....  Navíc devítka je zadarmo, a tak se stávám přeborníkem v
                        disciplíně: Hoď tašku do kouta a do setmění hraj streetball.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p>
                        Dostávám <strong>rozum.</strong> Aspoň si to myslím. :-)
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p class="hidden-lg-up">
                        Konečně se dozvídám, kdože je to ten Hrabal. Hustej týpek.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p>
                        Uchvátila mě <strong>Olomouc.</strong> <a href="http://www.ff.upol.cz"> Upisuji se</a> jí na 5 let.
                    </p>
                </div>


                <div class="right-container-text long-text">
                    <p class="hidden-lg-up margined-p">
                        Pořád zapáleně buším do klávesnice, ale poprvé své myšlenky přesouvám z
                        papíru na internet. Během všech dalších roků 21. století, které mi jsou vyměřeny, spravuju
                        hafo webů a některé i vytvářím. Amatérsky, ale <a href="http://www.15.oobtrebic.cz/">s láskou</a>.
                    </p>
                </div>

                <div class="right-container-text long-text">
                    <p class="margined-p">
                        Kráčím ve stopách Ámosových. No, <strong>zpočátku jsem spíše Igor Hnízdo.</strong> Bez sexuálních afér
                        a tělesných trestů. Amor mi však otevírá nejen srdce, ale i oči. A díky nově získanému nadhledu
                        se postupně Komenskému vydrápu aspoň ke kotníkům.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p class="hidden-lg-up margined-p">
                        Dostalo se mi daru <strong>koukat na svět opět dětskýma očima.</strong> Aspoň přes ramena mých rošťáku.
                        Díky synkovi už ani nemusím číst <a href="https://www.melvil.cz/kniha-zacnete-s-proc/">Sinka, aby věděl, že má začínat s proč</a>. Učím se to od něj.
                        Předtím mi každodenní workshopy na toto téma dopřávaly moje dcerky.
                    </p>
                </div>
                <div class="right-container-text long-text">
                    <p class="margined-p">
                        Konečně jsme si to s <strong>klávesnicí vyříkali.</strong> Ano, potřebujeme se, milujeme se, chceme se. Že
                        to otevření očí ale trvalo! Zkrátka po letech váhavého přešlapování se copywriting a vymýšlení
                        obsahových strategií stává mým denním chlebem. A že mi, panečku, chutná!
                    </p>
                </div>
            </div>
        </div>
        <!--// life story //-->


        <h1 class="o-veznikovi-h1">Nevěříte? Přesvědčte se sami.<br>
        <a href="/reference" class="o-veznikovi-h1">Třeba na webech, které jsem (mnohdy nejen) textoval.</a></h1>

<input type="hidden" class="jsonoff">

    </div>
</div>
